import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const repositoryRoot = fileURLToPath(new URL('../..', import.meta.url));
const apiDirectory = fileURLToPath(new URL('../src/api/', import.meta.url));
const openapiPath = `${repositoryRoot}/contracts/openapi.json`;

const document = JSON.parse(await readFile(openapiPath, 'utf8'));
const ast = await openapiTS(structuredClone(document));
const generated = `${astToString(ast).trimEnd()}\n`;

function rewriteRefs(value) {
  if (Array.isArray(value)) return value.map(rewriteRefs);
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value)
        // Ajv validates the oneOf branches; OpenAPI discriminator mappings are annotations it cannot compile.
        .filter(([key]) => key !== 'discriminator')
        .map(([key, child]) => [
          key,
          key === '$ref' && typeof child === 'string'
            ? child.replace('#/components/schemas/', '#/$defs/')
            : rewriteRefs(child),
        ]),
    );
  }
  return value;
}

const runtimeSchemas = {
  $id: 'https://motor-de-fluxo.local/contracts/schemas.json',
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $defs: rewriteRefs(document.components.schemas),
};
const validators = `/* Generated by scripts/generate-api.mjs. Do not edit. */
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import schemas from './schemas.json';

const ajv = new Ajv2020({
  coerceTypes: false,
  removeAdditional: false,
  useDefaults: false,
});
addFormats(ajv);
ajv.addSchema(schemas);

type JsonObject = Record<string, unknown>;

function isJsonObject(value: unknown): value is JsonObject {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

const UUID_KEY = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const SEED_TEXT = /^(0|[1-9][0-9]*)$/;
const MAX_SEED = 9223372036854775807n;

function normalizeUuidIdentity(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const bare = value.startsWith('urn:uuid:') ? value.slice('urn:uuid:'.length) : value;
  return UUID_KEY.test(bare) ? bare.toLowerCase() : null;
}

function hasValidGeneratedSampling(data: unknown): boolean {
  if (!isJsonObject(data) || !isJsonObject(data.sampling)) return false;
  const sampling = data.sampling;
  if (sampling.kind !== 'GENERATED_INPUT') return true;
  if (!isJsonObject(sampling.preparation_input)) return false;
  if (!Array.isArray(sampling.preparation_input.participants)) return false;
  if (!Array.isArray(sampling.repetitions)) return false;
  if (sampling.count !== sampling.repetitions.length) return false;
  const participantIds = sampling.preparation_input.participants.map((participant) =>
    isJsonObject(participant) ? normalizeUuidIdentity(participant.id) : null,
  );
  if (participantIds.some((participantId) => participantId === null)) return false;
  const expectedParticipants = new Set(participantIds as string[]);
  if (expectedParticipants.size !== participantIds.length) return false;
  const repetitionIds = new Set<string>();
  const seedsByParticipant = new Map(
    [...expectedParticipants].map((participantId) => [participantId, new Set<string>()]),
  );
  for (const repetition of sampling.repetitions) {
    if (!isJsonObject(repetition) || !isJsonObject(repetition.participant_seeds)) {
      return false;
    }
    const repetitionId = normalizeUuidIdentity(repetition.repetition_id);
    if (repetitionId === null || repetitionIds.has(repetitionId)) return false;
    repetitionIds.add(repetitionId);
    const suppliedParticipants = Object.keys(repetition.participant_seeds);
    if (
      suppliedParticipants.length !== expectedParticipants.size
      || suppliedParticipants.some((participantId) => !expectedParticipants.has(participantId))
    ) {
      return false;
    }
    for (const [participantId, seed] of Object.entries(repetition.participant_seeds)) {
      if (!UUID_KEY.test(participantId) || typeof seed !== 'string' || !SEED_TEXT.test(seed)) {
        return false;
      }
      if (BigInt(seed) > MAX_SEED) return false;
      const usedSeeds = seedsByParticipant.get(participantId);
      if (usedSeeds === undefined || usedSeeds.has(seed)) return false;
      usedSeeds.add(seed);
    }
  }
  const selectedRepetitionId = normalizeUuidIdentity(data.selected_repetition_id);
  return selectedRepetitionId !== null && repetitionIds.has(selectedRepetitionId);
}

ajv.addKeyword({
  keyword: 'validGeneratedSampling',
  schemaType: 'boolean',
  errors: false,
  validate: (enabled: boolean, data: unknown) => !enabled || hasValidGeneratedSampling(data),
});

export const validatePreviaRequest = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/PreviaRequest' });
export const validatePreviewEnvelope = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/PreviewEnvelope' });
export const validateReferenceExample = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/ReferenceExample' });
export const validatePreparationRequest = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/PreparationRequest' });
export const validatePreparationResponse = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/PreparationResponse' });
export const validateDiagnosticRequest = ajv.compile({
  allOf: [
    { $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/DiagnosticRequest' },
    { validGeneratedSampling: true },
  ],
});
export const validateJobSnapshot = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/JobSnapshot' });
export const validateDiagnosticEnvelope = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/DiagnosticEnvelope' });
`;

await mkdir(apiDirectory, { recursive: true });
await writeFile(`${apiDirectory}/generated.ts`, generated, 'utf8');
await writeFile(`${apiDirectory}/schemas.json`, `${JSON.stringify(runtimeSchemas, null, 2)}\n`, 'utf8');
await writeFile(`${apiDirectory}/validators.ts`, validators, 'utf8');
