import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';

const repositoryRoot = fileURLToPath(new URL('../..', import.meta.url));
const apiDirectory = fileURLToPath(new URL('../src/api/', import.meta.url));
const openapiPath = `${repositoryRoot}/contracts/openapi.json`;

const document = JSON.parse(await readFile(openapiPath, 'utf8'));
const ast = await openapiTS(structuredClone(document));
const generated = `${astToString(ast).trimEnd()}\n`;

function rewriteRefs(value) {
  if (Array.isArray(value)) return value.map(rewriteRefs);
  if (value !== null && typeof value === 'object') {
    return Object.fromEntries(
      Object.entries(value)
        // Ajv validates the oneOf branches; OpenAPI discriminator mappings are annotations it cannot compile.
        .filter(([key]) => key !== 'discriminator')
        .map(([key, child]) => [
          key,
          key === '$ref' && typeof child === 'string'
            ? child.replace('#/components/schemas/', '#/$defs/')
            : rewriteRefs(child),
        ]),
    );
  }
  return value;
}

const runtimeSchemas = {
  $id: 'https://motor-de-fluxo.local/contracts/schemas.json',
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  $defs: rewriteRefs(document.components.schemas),
};
const validators = `/* Generated by scripts/generate-api.mjs. Do not edit. */
import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import schemas from './schemas.json';

const ajv = new Ajv2020({
  coerceTypes: false,
  removeAdditional: false,
  useDefaults: false,
});
addFormats(ajv);
ajv.addSchema(schemas);

export const validatePreviaRequest = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/PreviaRequest' });
export const validatePreviewEnvelope = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/PreviewEnvelope' });
export const validateReferenceExample = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/ReferenceExample' });
export const validateEffectiveInput = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/EffectiveInput' });
export const validatePreparationRequest = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/PreparationRequest' });
export const validatePreparationResponse = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/PreparationResponse' });
export const validateCatalogResponse = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/CatalogResponse' });
export const validateCapabilities = ajv.compile({ $ref: 'https://motor-de-fluxo.local/contracts/schemas.json#/$defs/Capabilities' });
`;

await mkdir(apiDirectory, { recursive: true });
await writeFile(`${apiDirectory}/generated.ts`, generated, 'utf8');
await writeFile(`${apiDirectory}/schemas.json`, `${JSON.stringify(runtimeSchemas, null, 2)}\n`, 'utf8');
await writeFile(`${apiDirectory}/validators.ts`, validators, 'utf8');
